### ISSUE TITLE
Math docs

### ISSUE THREAD

**Issue by spencersalazar** [spencersalazar/chuck-ckdoc#6]

**Comment by ericheep** [comment]
Confused about `Math.ptor` and `Math.rtop`, they seem to be for converting a polar coordinate to a complex value, and vice versa, but their arguments call for an array of polar values and an array of complex values. Upon use, it only seems to return the size of the arrays.

**Comment by spencersalazar** [comment]
`ptor`/`rtop` modify in place, so the second argument to each gets the converted coordinates. Looking at the code it only converts `min(to.size(),from.size())` values, which seems a little goofy. So if the `from` array is shorter than not every value in `to` will be converted. The total number of conversions is returned.

**Comment by ericheep** [comment]
Cool, adding those notes and closing.
