### ISSUE TITLE
Machine docs

### ISSUE THREAD

**Issue by spencersalazar** [spencersalazar/chuck-ckdoc#7]

**Comment by ericheep** [comment]
`Machine.shreds` and `Machine.intsize` both raise syntax errors when called, I'm guessing they're unsupported, should I just leave their docs blank?

**Comment by spencersalazar** [comment]
These work for me, are you using version 1.3.5.2? `Machine.shreds` returns an array of the current `Shred` objects in the Virtual Machine. `Machine.intsize` returns the number of bits used for `int`s.

**Comment by ericheep** [comment]
Ah, they are working, I bet I was doing something dumb last night. Updated and closed.
